### PR TITLE
Changes for builder pattern

### PR DESCRIPTION
**Pull request by pknotfound**

### CODE REVIEW

**Comment by pknotfound** [comment]
Fixes #22 #23 #24 

@singpolyma, this pull request should fix all the three issues, specifying timeout, proxy and maxBodySize

You can use 

        OpenGraphParser.Builder(listener = this)
            .cacheProvider(OpenGraphCacheProvider(this))
            .showNullOnEmpty(true)
            .maxBodySize(1000000)
            .timeout(1000000)
            .jsoupProxy(JsoupProxy("<host>", 8000))
            .build()

to create the instance of OGP. You can still use 

        OpenGraphParser(
            listener = this,
            showNullOnEmpty = true,
            cacheProvider = OpenGraphCacheProvider(this)
        )

if there is not a need to specify other values.

I have tested this and is working as expected, can you confirm if all is working as expected?

Thanks

**Comment by singpolyma** [comment]
Instead of a new custom type `JsoupProxy` why not use the `java.net.Proxy` which jsoup does already support?

**Comment by pknotfound** [comment]
> Instead of a new custom type `JsoupProxy` why not use the `java.net.Proxy` which jsoup does already support?

Yes, that is because java.net and other packages are not available in Kotlin projects (Java 11). To avoid problems with any versions, we should keep external packages inside the lib code

**Comment by singpolyma** [comment]
Just tested this in my app and it seems to all work

**Comment by pknotfound** [comment]
> Just tested this in my app and it seems to all work

Great, thanks

**Pull request merged**
