### PR TITLE
added support for twitter links

### LINKED ISSUE #8: Some urls don't work.
This library is working quite good in many cases. It's snappy and doesn't seem to consume many resources. It works good on recyclerviews as well.

But, some urls, even popular ones such as www.google.com does not work. The return results are all 'null' and the error logs  says that 

'Unable to resolve host "xn--()-3y0jv63bvsjymf": No address associated with hostname'

Is there a workaround for this?

### LINKED ISSUE #12: Twitter og tags Problem
Hi,

First of all thank you for this useful library. But I couldn't get `og` tags for Twitter. I think this is`Jsoup` problem. Do you know anything about this?

### PR DESCRIPTION
**Pull request by pknotfound**

### CODE REVIEW

**Comment by pknotfound** [comment]
fixes #12 #8

**Comment by cagdasc** [comment]
When will you get new release version?

**Comment by pknotfound** [comment]
> When will you get new release version?

I will be releasing the version by today

**Comment by pknotfound** [comment]
@cagdasc I have released the new version. 
Thank you for reporting the issue.

**Pull request merged**
